---
namespace: es_support_mg22
name: passwork_api
version: 0.0.7
readme: README.md
authors:
  - EFIS
description: Ansible python modules for Passwork API
license: "MIT"
tags:
  - passwork
repository: https://github.com/es-support-mg22/passwork_api
documentation: ""
homepage: https://github.com/es-support-mg22/passwork_api